SLIB-51 - implemented RP API v3 session status request handling
SK-EID/smart-id-java-client pull request #88
Opened 2024-10-17 08:41 UTC by ragnarhaide

2024-10-17 20:03 UTC, umuser requested changes

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/rest/SessionStatusPoller.java
> +        logger.debug("Starting to poll session status for session " + sessionId);
java-clientis on logback kasutusel, ehk saad kasutada parameetritega logimist. 
Ehk saaksid midagi sellist teha. 
`logger.debug("Starting to poll session status for session {} ", sessionId);`

Vaata teised logimise kohad ka üle

2024-10-17 20:03 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderServiceTest.java
> +    private static final String DEMO_HOST_SSL_CERTIFICATE = "MIIGxTCCBa2gAwIBAgIQB//0m9ljohCn8LB5KDcE1jANBgkqhkiG9w0BAQsFADBZ\n" +
Demo sert on fails. Loe see FileUtil-iga sisse. Demo-sert kestab ainult aasta ja siis on lihtsam seda testide jaoks kordada teha, kui see ainult failis on.

2024-10-17 20:03 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderServiceTest.java
> +    void documentConfigureTheClient() {
Mida sa testid siin?

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/SignableData.java
> +package ee.sk.smartid;
See peaks ainult v2 olema, selles classis on meetod calculateVerificationCode, mida on ainult v2 jaoks vaja. Tee v3 jaoks eraldi object

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/SignableHash.java
> +package ee.sk.smartid;
V3 jaoks ka ei ole vaja calculateVerificationCode, et samamoodi lisa v3 jaoks uus

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/rest/SessionStatusPoller.java
> +    public SessionStatusPoller(SmartIdConnector connector, SmartIdRequestBuilderService requestBuilder) {
Ma hetkel ei saa aru, miks sa SmartIdRequestBuilderService-i siia lisasid?

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/rest/SmartIdConnector.java
> -     * Set the session status response socket open time
Kuhu need java-docid kadusid?

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +    private void validateCertificate(SessionCertificate sessionCertificate, String requestedCertificateLevel) {
Lisa teste juurde

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +        if ("OK".equalsIgnoreCase(endResult)) {
OK korral peaks documentNumber ka olemas olema.

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +    private void handleSessionEndResultErrors(String endResult) {
Lisa sellele ka testid

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/rest/dao/SessionResult.java
> +  private String signatureProtocol;
See ei peaks SessionResult all olema

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +        if ("OK".equalsIgnoreCase(endResult)) {
InteractionFlow on ka OK väärtuse korral vaja valideerida

2024-10-17 20:03 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/rest/dao/SessionSignature.java
> +    private String hashAlgorithm;
See peaks eraldi objektis olema. Spekis on see signatureAlgorithmParameters parameeter.

2024-10-18 06:45 UTC, ragnarhaide commented on src/main/java/ee/sk/smartid/v3/rest/SessionStatusPoller.java
> +    public SessionStatusPoller(SmartIdConnector connector, SmartIdRequestBuilderService requestBuilder) {
Tähelepanematusest jäänud lõpus. Üks sellistest kohtadest ja juhustest, mis arenduse käigul valesti läinud, aga unustanud kohe eelmadada ja hiljem polnud ka meeles :D

2024-10-18 07:18 UTC, ragnarhaide commented on src/test/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderServiceTest.java
> +    void documentConfigureTheClient() {
see ka kogemata katsetamisest ja tähelepanematusest jäänud

2024-10-19 16:06 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderServiceTest.java
> +    private static final String DEMO_HOST_SSL_CERTIFICATE = "MIIGxTCCBa2gAwIBAgIQB//0m9ljohCn8LB5KDcE1jANBgkqhkiG9w0BAQsFADBZ\n" +
Vaata testide all on ee.sk.smartid.v2.FileUtil

2024-10-19 17:56 UTC, umuser requested changes

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +        if (sessionStatus.getSignature() == null) {
Vaata need valideerimised üle `..getSignature() == null` ja `..getCert() == null`.
`validateSessionResult(...)`, OK väärtuse korral kasutab `getSignature()` päringut ja `getCert()` ka juba valideeritakse. Teisel juhul tuleb endResult tulemuse pealt juba viga.

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +            if (sessionResult.getDocumentNumber() == null || sessionResult.getDocumentNumber().isEmpty()) {
ee.sk.smartid.util.StringUtil::isEmpty saaksid siin ka kasutada

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +            if (sessionStatus.getInteractionFlowUsed() == null || sessionStatus.getInteractionFlowUsed().isEmpty()) {
Siin ka saad kasutada StringUtil::isEmpty(..)

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +            if (sessionStatus.getInteractionFlowUsed() == null || sessionStatus.getInteractionFlowUsed().isEmpty()) {
Kata see valideerimine ka testiga

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +        if ("ACSP_V1".equalsIgnoreCase(signatureProtocol)) {
ACSP_V1 ja RAW_DIGEST_SIGNATURE võiksid enumiks teha

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +        } else if ("RAW_DIGEST_SIGNATURE".equalsIgnoreCase(signatureProtocol)) {
Lisa selle jaoks ka test

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +            MessageDigest digest = MessageDigest.getInstance("SHA-256");
Millest SHA-256 tuli? 

> The digest algorithm to use is specified in signature.digestAlgorithm. The signature scheme that was used to generate the signature based on the digest is specified in signature.signatureScheme.

Spekis on veel osad kohad uuendamata. digestAlgorithm asendati signatureAlgorithm'iga ja signatureSchema peaks olema nüüd hashAlgorithm. Speki järgi peaksid kasutama hashAlogithm väärtust.

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +        if (!"sha512WithRSAEncryption".equals(signatureAlgorithm)) {
signatureAlgorithm väärtus ei ole konstantne. Lubatud võimalikud väärtused https://sk-eid.github.io/smart-id-documentation/rp-api/3.0.0/signature_protocols.html#supported_signature_algorithms

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +        if ("ACSP_V1".equalsIgnoreCase(signatureProtocol)) {
Enum on juba olemas, saad siin kasutada.

2024-10-19 17:56 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/rest/SmartIdRestConnector.java
> +    public SessionStatus getSessionStatus(String sessionId, long timeoutMs) throws SessionNotFoundException {
sessionStatusResponseSocketOpenTimeValue peaks täitma parameetri timeoutMs mõtet ja seda ei ole vaja funktsioonis ette anda

2024-10-19 17:56 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/rest/SmartIdRestConnectorTest.java
> +        MatcherAssert.assertThat(sessionStatus.getCert().getValue(), startsWith("MIIHhjCCBW6gAwIBAgIQDNYLtVwrKURYStrYApYViTANBgkqhkiG9"));
Lisa staatiline import

2024-10-19 17:56 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/rest/SmartIdRestConnectorTest.java
> +    void getNotExistingSessionStatus() {
Paranda nimetust, tegemist on ikkag getRunninSessionStatus päringuga, aga tulemus on NotFound

2024-10-19 17:56 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/rest/SmartIdRestConnectorTest.java
> +class SmartIdRestConnectorTest {
Võiks siin jätkata ka järjestusega, et positiivse tulemusega testid on eespool ja veaolukordade testid on tagapool. Saaksid veaolukordade jaoks selgusemõttes ka @Nested klassi tekitada.

2024-10-19 17:56 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderServiceTest.java
> +    static class EndResultArgumentsProvider implements ArgumentsProvider {
Täpsusta nimetust, tegemist on ikkagi veaolukordadega.

2024-10-19 17:56 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderServiceTest.java
> +class SmartIdRequestBuilderServiceTest {
Võta ka siin kasutusele @Nested klassid. Saad signatuuri ja sertifikaatide valideerimised grupperida vastavatesse nested klassidesse.

2024-10-23 19:51 UTC, umuser requested changes

2024-10-23 19:51 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +        if (SignatureProtocol.ACSP_V1.name().equalsIgnoreCase(signatureProtocol)) {
Speki järgi peaks olema SignatureProtocoli väärtus suuretähega.

2024-10-23 19:51 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/rest/SmartIdConnector.java
> +    SessionStatus getSessionStatus(String sessionId) throws SessionNotFoundException;
Lisa sellele java doc

2024-10-23 19:51 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +        List<String> allowedSignatureAlgorithms = Arrays.asList("sha256WithRSAEncryption", "sha384WithRSAEncryption", "sha512WithRSAEncryption");
Kasuta Seti siin, sul on ainult unikaalsed väärtused.

2024-10-23 19:51 UTC, umuser commented on README.md
> +### Successful response after completion, notification-based flow, protocol RAW_DIGEST_SIGNATURE
RAW_DIGEST_SIGNATURE tagstatakse signature sessions status OK vastuses dynamic link ja notification-based jaoks

2024-10-23 19:51 UTC, umuser commented on README.md
> +### Successful response after completion, dynamic flow, protocol ACSP_V1
ACSP_V1 tagastatakse authentication sessions statuse OK vastuses dyanmic-link ja notification-based flow jaoks.

2024-10-23 19:51 UTC, umuser commented on README.md
> +client.setHostUrl("https://sid.demo.sk.ee/smart-id-rp/v3/");
siin peaks ka truststore olema mainitud, ilma serdita päringud ei toimi

2024-10-25 19:12 UTC, umuser reviewed
Uuenda Changelog ka ära

2024-10-28 06:57 UTC, umuser commented on CHANGELOG.md
> +- Added handling for session status request handling. View V3 section in README.md for more information.
`Added support for handling session status requests` loeks veits paremini

2024-10-29 05:40 UTC, merged