Add dynamic link based certificate choice request handling
SK-EID/smart-id-java-client pull request #90
Opened 2024-10-23 03:57 UTC by ragnarhaide

2024-10-23 20:17 UTC, umuser requested changes

2024-10-23 20:17 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/rest/dao/CertificateChoiceResponse.java
> +public class CertificateChoiceResponse implements Serializable {
Lisa selle nimetusse DynamicLink

2024-10-23 20:17 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/CertificateRequestBuilderService.java
> +public class CertificateRequestBuilderService {
Siin võiks ka nimetuses olla DynamicLink

2024-10-23 20:17 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/CertificateRequestBuilderService.java
> +public class CertificateRequestBuilderService {
Nimetuste juures peaks sead ka silmas pidama, et builder on ainult request jaoks, mis tekitab vastava sessiooni. Kuna vahapeal peab näitama kasutajale QR-code ja/või Linki response väärtuste pealt ( sessionToken ja sessionSecret), siis alles pärast tuleb sessionId järgi sessiooni tulemus pärida. Ehk siis see võiks olla stiilis DynamicLinkCertificateSessionRequestBuilder.

2024-10-23 20:17 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/CertificateRequestBuilderService.java
> +            sessionStore.storeSession(response.getSessionID(), response.getSessionToken(), response.getSessionSecret());
Session store mõte oli maha märkida, et certificate session request tehti, ehk see võiks toimuda siis,  kui certificate choice session status response on OK. Ajutiselt salvestavate andmete osas piisaks sessionId-st ja nt value certificate-choice.

2024-10-23 20:17 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/CertificateRequestBuilderService.java
> +    private final SessionStatusPoller sessionStatusPoller;
Pollerit ei ole siin vaja.

2024-10-23 20:17 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/rest/SmartIdRestConnectorTest.java
> +        @Test
Saaksid nende testide osas @Nested classi gruppeeringut muuta, näiteks session status osa on koos ja certificate choice osa on koos. Proovi kuidas loogilisem tundub.

2024-10-28 07:14 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/DynamicLinkCertificateRequestBuilder.java
> +        SessionStatus sessionStatus = sessionStatusPoller.fetchFinalSessionStatus(response.getSessionID());
SessionStatusPollerit ei saa siin klassis kasutada, sest `sessionStatusPoller.fetchFinalSessionStatus(..)` ei tööta kui kasutajale ei ole veel jõutud kuvada dünaamiliseid väärtuseid, mis genereeritakse DynamicLinkCertificateChoiceResponse olevate väärtuste pealt.

2024-10-28 09:32 UTC, umuser requested changes

2024-10-28 09:32 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/SessionStore.java
> +    void storeSession(String sessionId, String sessionToken, String sessionSecret);
Su tehtud sessionStore mõte ei ole sessionTokeni ja sessionStorei maha salvestamine.

2024-10-28 09:32 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/SmartIdClient.java
>      public static SSLContext createSslContext(List<String> sslCertificates)
Liiguta staatilised meetodid classi lõppu

2024-10-28 09:32 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/SmartIdClient.java
> +    public DynamicLinkCertificateRequestBuilder createCertificateRequest() {
Lisa selle jaoks ka testid

2024-10-28 09:32 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/SmartIdClient.java
>      public static SSLContext createSslContext(List<String> sslCertificates)
Jäi enne tegemata, aga public truststore ja SSLiga meetodid peaks ka olema javadociga

2024-10-28 11:54 UTC, umuser commented on src/test/java/ee/sk/smartid/SignableHashTest.java
> -package ee.sk.smartid.v2;
See testib v2 SignableData classi ja peaks olema v2 package-is

2024-10-28 11:54 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/DigestCalculator.java
> +public class DigestCalculator {
Selle klassi võiks üldiseks liigutada. HashType on juba üldine. Praegust v2 ja v3 on sama implementatsioon

2024-10-28 11:54 UTC, umuser commented on src/test/java/ee/sk/smartid/v2/SmartIdDemoIntegrationTest.java
> +import ee.sk.smartid.v2.SmartIdDemoCondition;
Mul näitab see unused import

2024-10-28 11:54 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/DynamicLinkCertificateRequestBuilder.java
> +public class DynamicLinkCertificateRequestBuilder {
Lisa javadocid ka

2024-10-28 11:54 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/DynamicLinkCertificateRequestBuilder.java
> +    public DynamicLinkCertificateRequestBuilder withRequestProperties(RequestProperties requestProperties) {
Võta selle handlimine v2 pealt üle, vaata `CertificateRequestBuilder::withShareMdClientIpAddress(boolean)`

2024-10-28 11:56 UTC, umuser commented on README.md
> +* Query parameter: `timeoutMs` (optional, long poll timeout value, default is halfway between max and min values)
Mis on max and min values?

2024-10-28 12:11 UTC, umuser commented on README.md
> +System.out.println("Session completed with result: " + sessionStatus.getResult().getEndResult());
Kasuta taanet, et paremini näites koodi kuvada.

2024-10-28 12:23 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +            if (!requestedCertificateLevel.equals(sessionCertificate.getCertificateLevel())) {
Siin võib probleem tekkida. Kui päritakse QSCD certificateLeveliga, siis praegust dokumentatsiooni järgi tundub, et sama levelit ei tagastata. ADVANCED ja QUALIFIED on ainult sessions status response kirjelduses.

2024-10-28 12:31 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderService.java
> +            if (!requestedCertificateLevel.equals(sessionCertificate.getCertificateLevel())) {
Küsisin Jalukse käest üle, mis väärtus tuleb QSCDga pärimisel ja ta arvas, et QUALIFIED, ehk siin peaks seda võrldust täiendama.

2024-10-28 13:22 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/rest/dao/DynamicLinkCertificateChoiceResponse.java
> +public class DynamicLinkCertificateChoiceResponse implements Serializable {
Nimetus võiks olla veel täpsem `DynamicLinkCertificateChoiceSessionResponse`

2024-10-29 06:54 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/CertificateChoiceStatusStore.java
> +     * @param userSessionId The session ID associated with the certificate choice request.
Kirjeldus võiks konkreetsem olla

2024-10-29 06:54 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/SmartIdClient.java
>      public static SSLContext createSslContext(List<String> sslCertificates)
> Liiguta staatilised meetodid classi lõppu

See veel tegemata

2024-10-29 06:55 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/DigestCalculator.java
> +public class DigestCalculator {
Vaata, et selle testid ka oleks õiges kohas.

2024-10-29 07:01 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/DynamicLinkCertificateChoiceSessionRequestBuilder.java
> +    /**
Vaata see kirjeldus üle

2024-10-29 07:04 UTC, umuser commented on README.md
> +
üleliigsed tühjad read

2024-10-29 07:12 UTC, umuser commented on README.md
> +// Track certificate choice status in CertificateChoiceStatusStore without storing sessionId or sessionToken
CertificateChoiceStatusStore on ainult teegi seisukohalt vajalik, et valideerida õige flow-d. Readme-s peaks olema info, mis on teegi kasutajale vajalik. Teegi kasutamisel tuleb rakenduse pool salvestada response-i tulemus ( sessionId, sessionToken, sessionSecret), aga nende hoiustamise ülesanne jääb teegi kasutajale. Siin saab välja tuua, et sessionId tuleks kasutada SessionStatus pärimiseks. SessionSecret tuleb hoiustada backendis turvaliselt.

2024-10-29 07:37 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/service/SmartIdRequestBuilderServiceTest.java
> +            Method method = SmartIdRequestBuilderService.class.getDeclaredMethod("validateCertificate", SessionCertificate.class, String.class);
See ei ole hea. Üldiselt kui vaja otse private meetodit testida, siis see viitab juba koodidisaini veale ja oleks vaja ümber teha.

2024-10-29 08:15 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/SmartIdClient.java
> +                certificateChoiceStatusStore.storeSession(response.getSessionID(), "certificate-choice");
Vale ID on kasutuses. Me peaks kasutama id, mis on lõppkasutajaga sessiooniga seotud. Need ID, mis me RP API poolt saame on ainult ühe konkreetse protsessi vältel kasutusel. Nt certificate choice sessiooni alustamine ja selle pärimine. Aga meil on vaja seost certificate choice sessiooni alustamine, selle õnnestumine ja siis signature sessiooi alustamine ja selle õnnestumine. 

Ma pakun, et teeks siin variandi, et kuna seda state-i on keeruline hoiustada ja on sellega praegust palju segadust, et siis selle taski raames hetkel seda ei implementeeri ja tekitame analüüsi taski, et seda läbi mõelda. Praegust paneme README-s ainult kirja, et certificate choice päringule peab järgnema notification-based signature choice.

2024-10-30 10:52 UTC, umuser commented on src/test/java/ee/sk/smartid/SignableHashTest.java
> -package ee.sk.smartid.v2;
See veel tegemata

2024-10-30 13:40 UTC, umuser requested changes

2024-10-30 13:40 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/service/DynamicLinkCertificateChoiceSessionRequestBuilder.java
> +     * Note: The sessionToken and sessionSecret are not stored within this class and should be securely handled
Note osa tundub üleliigne.

2024-10-30 13:40 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/CertificateChoiceStatusStore.java
> +public interface CertificateChoiceStatusStore {
Kas sa tekitasid selle store-i jaoks analüüsi taski?

2024-10-30 13:40 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/CertificateChoiceStatusStore.java
> +public interface CertificateChoiceStatusStore {
Vb praegust ei ole vaja seda store-i ka alles hoida. Nt kui analüüsi käigus selgub, et oleku hoidmine teeb teegi kasutamise liiga keeruliseks ja ei olegi mõtet implementeerida.

2024-10-30 13:40 UTC, umuser commented on README.md
> +### Successful response after completion, dynamic flow, protocol ACSP_V1
Enne oli õige, ACSP_V1 tagastatakse authentication session status ok tulemuse korral

2024-10-30 13:40 UTC, umuser commented on README.md
> +### Successful response after completion, notification-based flow, protocol RAW_DIGEST_SIGNATURE
Enne oli õige, RAW_DIGEST_SIGNATURE tagastatakse signature session status ok tulemuse korral.

2024-10-30 13:40 UTC, umuser commented on README.md
> +The request parameters for the dynamic link certificate choice session are the same as those for the notification-based certificate choice request.
`those for the notification-based certificate choice request` ei ole vaja hetkel mainida. Notification-based certificate choice arendus tuleb hiljem.

2024-10-30 13:40 UTC, umuser commented on README.md
> +        var builder=new CertificateRequestBuilderService(client.getSmartIdConnector(),client.getSessionStatusPoller())
builderi otse kasutamise asemel peaks olema `client.createDynamicLinkCertificateRequest().with(....`

2024-10-30 13:40 UTC, umuser commented on README.md
> +import ee.sk.smartid.v3.rest.SessionStatusPoller;
importe ei ole vaja

2024-10-30 13:40 UTC, umuser commented on README.md
>  Jump to [Generate QR-code and dynamic link](#generating-qr-code-or-dynamic-link) to see how to generate QR-code or dynamic link from the response.
`Jump to ..` peaks olema #### Initiating authentication session with semantics identifier osa lõpus.

Dynamic link authentication osa on merge käigus eraldi läinud - `#### Initiating authentication session with document number` ja `### Initiating anonymous authentication session` peaksid ka olema `### Examples of performing authentication` osa all

2024-10-30 13:40 UTC, umuser commented on README.md
> +## Storing Session Information
Seda ei ole ka hetkel vaja kui analüüsi task tuleb.

2024-10-30 13:40 UTC, umuser commented on README.md
> +## Additional Information
Selle kirjeldust oleks vaja uuendada

2024-10-31 06:35 UTC, ragnarhaide commented on src/main/java/ee/sk/smartid/v3/CertificateChoiceStatusStore.java
> +public interface CertificateChoiceStatusStore {
> Kas sa tekitasid selle store-i jaoks analüüsi taski?

jah, https://jira.sk.ee/browse/SLIB-70

2024-10-31 11:36 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/CertificateChoiceStatusStore.java
> +public interface CertificateChoiceStatusStore {
Taski all tuleks ka lisada koos kirjeldusega.

2024-10-31 11:51 UTC, umuser commented on README.md
> +        CertificateChoiceResponse response=builder.initiateCertificateChoice();
Paranda see ka ära. Sul ei ole praegust builderit eelnevalt mainitud.

2024-10-31 11:51 UTC, umuser commented on README.md
> +## Additional Information
RequestProperties väärtustamise tegid ju ümber, et pigem on ainult shareMdClientIpAddress väärtustamist vaja välja tuua.

2024-10-31 11:54 UTC, umuser requested changes

2024-10-31 11:54 UTC, umuser commented on README.md
> +        .withRequestProperties(new RequestProperties().withShareMdClientIpAddress(true));
withRequestProperties -> withShareMdClientIpAddress

2024-10-31 11:54 UTC, umuser commented on README.md
> +CertificateRequest request = new CertificateRequest();
Kasuta näites builderit.

2024-10-31 20:12 UTC, umuser commented on README.md
> +        CertificateChoiceResponse response=builder.initiateCertificateChoice();
Response object on ka muutunud

2024-11-01 07:13 UTC, umuser approved these changes

2024-11-01 09:00 UTC, merged