SLIB-48 - added notification based authentication request handling
SK-EID/smart-id-java-client pull request #94
Opened 2024-11-15 13:49 UTC by ragnarhaide

2024-11-25 06:01 UTC, umuser requested changes

2024-11-25 06:01 UTC, umuser commented on README.md
> +## Examples of performing notification authentication
TOCi tuleks ka täiendad

2024-11-25 06:01 UTC, umuser commented on README.md
> +        .withSharedMdClientIpAddress(true)
Seda ei ole vaja iga näidis päringuga näidata. Pigem võiks selle kasutamiseks ainult eraldi kirjeldus olla.

2024-11-25 06:01 UTC, umuser commented on README.md
> +String sessionId = authenticationSessionResponse.getSessionID();
Selle juures peaks ka kirjeldus olema. Kasutatakse sessions statuse pärimiseks

2024-11-25 06:01 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/NotificationAuthenticationSessionRequestBuilder.java
> +    public NotificationAuthenticationSessionRequestBuilder withRelyingPartyUUID(String relyingPartUUID) {
javadoc on puudu

2024-11-25 06:01 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/NotificationAuthenticationSessionRequestBuilder.java
> +            throw new SmartIdClientException("Either documentNumber or semanticsIdentifier must be set. Anonymous signing is not allowed.");
"Anonymous signing is not allowed" - antud flow peaks olema authentication, aga muidu piisaks ka ainult "Either documentNumber or semanticsIdentifier must be set" kirjeldusest

2024-11-25 06:01 UTC, umuser commented on src/main/java/ee/sk/smartid/v3/NotificationAuthenticationSessionRequestBuilder.java
> +            logger.error("Session ID is missing from the notificationAuthenticationSessionResponse");
Meil ei ole vaja tagastada objekti nime veateates

2024-11-25 06:01 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/NotificationAuthenticationSessionRequestBuilderTest.java
> +            var exception = assertThrows(SmartIdClientException.class, () -> {
UnprocessableSmartIdResponseException-i peaks response-i testides valideerima

2024-11-25 06:01 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/NotificationAuthenticationSessionRequestBuilderTest.java
> +        private void initAuthentication() {
Peaks ühtlustama, kas testides kasutada builderit otse või seda abi-meetodit

2024-11-26 08:27 UTC, ragnarhaide commented on README.md
> +## Examples of performing notification authentication
Seda võiks teha ehk https://jira.sk.ee/browse/SLIB-56 raames. Hetkel puuduvad TOC-ist kõik v3.0 osad. 
Ma lisaks veel notification certificate choice osa ka ära, siis oleks kogu dynamic ja notification osa olemas. Võibolla siis veel vaja värske pilguga üle vaadata, et kuidas erinevad lõigud loogilised oleks ja vajadusel ümber tõsta. Siis saaks lõpliku ja täieliku TOC-i v3 kohta ka teha.

2024-11-29 11:17 UTC, umuser approved these changes

2024-11-29 11:17 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/rest/SmartIdRestIntegrationTest.java
Test numbrid töötavad notification voogudega, saaks siia lisada notification-based authentication voo algusest lõpuni

2024-11-29 11:17 UTC, umuser commented on src/test/java/ee/sk/smartid/v3/rest/SmartIdRestIntegrationTest.java
Kuna refacto osas tuleb mingeid täiendusi authentication response valideerimisse, siis vb lisada see testi tegemise info notificationi refacto taski.

2024-11-30 06:48 UTC, merged